language: node_js
node_js:
  - "8"
os:
  - linux
  - osx
sudo: false
after_success:
  - codecov -f coverage/coverage-final.json
install:
  - npm update
  - npm install
script:
 - npm run lint
 - npm test
